import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Item from '../components/Item/Item';
import List from '../components/List/List';
import styles from '../styles/Home.module.css'

export default function Home() {
    let [data, setData] = useState([]);
    
    async function fetchData() {
        let response = await fetch('/api/todoist')
        let json = await response.json()

        setData(json)
    }

    useEffect(() => {
        fetchData()
    }, [])

    return <div className={ styles.container }>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={ styles.main }>
            <List items={ data } />
        </main>
    </div>
}
